### ISSUE TITLE
Improve README of examples

### ISSUE THREAD

**Issue by marcotama** [dstil/surround#51]
I had a look at the examples, but I still have no idea how to interpret them. I reckon that expanding the READMEs to describe what the example process does will be helpful in understanding how one's project pieces fit in the Surround framework.

I suppose that a couple of data analysis examples would also be very helpful, at least for me. I am thinking about "label cats vs dogs using a simple model", which teaches users where the processing code goes, how the config file is used in the context etc.

Another example could be a more complex routine, for example the bibs project, where several parts are at work, e.g. locating the bib, reading the numbers within etc.

**Comment by AkshatBajaj** [comment]
I think this issue is addressed now that we have a lot of examples. Moreover, PR #63 also added description.
